CREATE TABLE records (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    telegram VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    option VARCHAR(50) NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

